# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title.html

# Setup
title:            Nate Winn
tagline:          'Still learning'
description:      'My thoughts on coding, technology, design and the like. Written by <a href="https://twitter.com/natewinn" target="_blank">@natewinn</a>.'
url:              http://natewinn.com

author:
  name:           'Nate Winn'
  url:            https://twitter.com/natewinn

paginate:         5

# Custom vars

github:
  repo:           https://github.com/natewinn

picture:
  source: assets/images/_fullsize
  output: generated
  markup: picturefill
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
